// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "FlashWindow.h"

/////////////////////////////////////////////////////////////////////////////
// CShockwaveflash1

IMPLEMENT_DYNCREATE(CFlashWindow, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CShockwaveflash1 properties

/////////////////////////////////////////////////////////////////////////////
// CShockwaveflash1 operations
